"""Canonical Master Research Backlog entries for Darwin.

Contains the 44 canonical research items spanning:
1. MONETIZATION (12 items linked directly to canonical Portfolio 01 opportunities)
2. BUSINESS_VALIDATION (5 items covering DFG business concepts requiring validation)
3. TECHNOLOGY_SCOUT (16 items evaluating external software for DFG leverage)
4. INTELLIGENCE_CAPABILITIES (11 items defining future intelligence layers)

Preserves strict provenance tracking; items lacking tracked repository documents
explicitly record empty provenance references so research requirements are emitted
rather than fabricated citations.
"""

from __future__ import annotations

from darwin.backlog.schemas import (
    BacklogCategory,
    BacklogPriority,
    BacklogStatus,
    ResearchBacklogItem,
)

CANONICAL_MASTER_BACKLOG_ITEMS: list[ResearchBacklogItem] = [
    # =========================================================================
    # 1. MONETIZATION (Linked directly to Portfolio 01)
    # =========================================================================
    ResearchBacklogItem(
        item_id="RBACK-MON-001",
        title="FP Labs External Services Commercialization",
        category=BacklogCategory.MONETIZATION,
        priority=BacklogPriority.P0_NOW,
        status=BacklogStatus.READY,
        objective="Package existing DFG workflow automation, webhook execution, and trading dashboard engineering into billable client services.",
        origin="Portfolio 01 Baseline",
        provenance_refs=["docs/runtime/monetization-opportunity-portfolio.md"],
        related_opportunity_id="fp-labs-external-services",
        related_project="FP Labs",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "What hourly or sprint billing rates does the boutique automation market support?",
            "What is Daniel's weekly delivery capacity for external client engagements?",
        ],
        expected_output="Deterministic rate card and fixed-scope delivery packages.",
        decision_type="COMMERCIAL_ALLOCATION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-MON-002",
        title="Commercial Product Photography Studio Monetization",
        category=BacklogCategory.MONETIZATION,
        priority=BacklogPriority.P0,
        status=BacklogStatus.READY,
        objective="Validate commercial photography studio service offerings, day rates, and turnaround times in Mexico City.",
        origin="Portfolio 01 Baseline",
        provenance_refs=[
            "docs/runtime/monetization-opportunity-portfolio.md",
            "_1946_MEZCALES 101B_para_andres copia.jpg",
        ],
        related_opportunity_id="commercial-product-photography",
        related_project="Commercial Photography",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "What are prevailing CDMX commercial studio day rates for beverage/product shoots?",
            "What labor hours are required per final retouched deliverable?",
        ],
        expected_output="Commercial photography service tiers and sample brief quote.",
        decision_type="COMMERCIAL_ALLOCATION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-MON-003",
        title="Cinema Collection Equipment Rental Deployment",
        category=BacklogCategory.MONETIZATION,
        priority=BacklogPriority.P0_NOW,
        status=BacklogStatus.READY,
        objective="Deploy owned cinema camera and optical gear onto rental networks in CDMX with verified deposit/insurance coverage.",
        origin="Portfolio 01 Baseline",
        provenance_refs=["docs/runtime/monetization-opportunity-portfolio.md"],
        related_opportunity_id="cinema-collection-equipment-rental",
        related_project="Cinema Collection",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "What are verified daily rental rates for camera packages in CDMX?",
            "What platform commission and insurance structures govern peer rentals?",
        ],
        expected_output="Listing-ready equipment manifest and rental agreement terms.",
        decision_type="COMMERCIAL_ALLOCATION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-MON-004",
        title="Trading Strategy Hardening & Forward Paper Validation",
        category=BacklogCategory.MONETIZATION,
        priority=BacklogPriority.P0,
        status=BacklogStatus.READY,
        objective="Paper-validate EMA trend, RSI mean-reversion, and VWAP strategies with real fee drag and execution slippage before live capital allocation.",
        origin="Portfolio 01 Baseline",
        provenance_refs=[
            "docs/runtime/monetization-opportunity-portfolio.md",
            "docs/runtime/trading-paper-validation-spec.md",
        ],
        related_opportunity_id="trading-strategy-hardening",
        related_project="Trade Executor",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "What is the net forward expectancy after Binance taker fees (0.10% round-trip)?",
            "What is the realistic order execution slippage during volatile sessions?",
        ],
        expected_output="30-day continuous paper execution log and equity curve.",
        decision_type="COMMERCIAL_ALLOCATION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-MON-005",
        title="TikTok Shop Affiliate Creative Pipeline",
        category=BacklogCategory.MONETIZATION,
        priority=BacklogPriority.P1_HIGH,
        status=BacklogStatus.NEEDS_EVIDENCE,
        objective="Produce automated high-volume product showcase creative for TikTok Shop affiliate commissions.",
        origin="Portfolio 01 Baseline",
        provenance_refs=["docs/runtime/monetization-opportunity-portfolio.md"],
        related_opportunity_id="tiktok-shop-affiliate-creative",
        related_project="Production Engine",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "What are current TikTok Shop creator account gating requirements?",
            "What average commission rates and view-to-GMV conversions exist across categories?",
        ],
        expected_output="Creator qualification checklist and pilot product list.",
        decision_type="COMMERCIAL_ALLOCATION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-MON-006",
        title="FPCriptoClub Audience Monetization",
        category=BacklogCategory.MONETIZATION,
        priority=BacklogPriority.P1,
        status=BacklogStatus.NEEDS_EVIDENCE,
        objective="Monetize crypto community through exchange affiliate links, VIP Telegram signals, and digital education products.",
        origin="Portfolio 01 Baseline",
        provenance_refs=["docs/runtime/monetization-opportunity-portfolio.md"],
        related_opportunity_id="fpcriptoclub-monetization",
        related_project="Trading Dashboard",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "What is the active community conversion rate to paid tiers?",
            "What monthly churn rate characterizes VIP trading channels?",
        ],
        expected_output="Community monetization conversion model and pricing tiers.",
        decision_type="COMMERCIAL_ALLOCATION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-MON-007",
        title="Billy The Trader Character Brand Monetization",
        category=BacklogCategory.MONETIZATION,
        priority=BacklogPriority.P1,
        status=BacklogStatus.NEEDS_EVIDENCE,
        objective="Monetize the fictional trading character Billy The Trader through content publishing and commercial sponsorships.",
        origin="Portfolio 01 Baseline",
        provenance_refs=["docs/runtime/monetization-opportunity-portfolio.md"],
        related_opportunity_id="billy-the-trader",
        related_project="Billy Production Engine",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "What is the audience velocity achievable with automated daily short-form videos?",
            "What sponsorship rates exist for synthetic financial creator properties?",
        ],
        expected_output="Audience acquisition roadmap and sponsorship rate benchmark.",
        decision_type="COMMERCIAL_ALLOCATION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-MON-008",
        title="Production Engine Economic Impact Measurement",
        category=BacklogCategory.MONETIZATION,
        priority=BacklogPriority.P1,
        status=BacklogStatus.NEEDS_EVIDENCE,
        objective="Quantify internal labor cost reduction and external batch rendering service revenue from Billy Production Engine.",
        origin="Portfolio 01 Baseline",
        provenance_refs=["docs/runtime/monetization-opportunity-portfolio.md"],
        related_opportunity_id="production-engine-acceleration",
        related_project="Billy Production Engine",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "What is the exact compute cost per rendered batch job?",
            "How much labor time is saved compared to manual timeline editing?",
        ],
        expected_output="Unit production economics breakdown and agency service rate card.",
        decision_type="COMMERCIAL_ALLOCATION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-MON-009",
        title="Airbnb Experiences Guided Photography Experiences",
        category=BacklogCategory.MONETIZATION,
        priority=BacklogPriority.P1,
        status=BacklogStatus.NEEDS_EVIDENCE,
        objective="Host guided photo walks and portrait experiences booked through Airbnb Experiences in Mexico City.",
        origin="Portfolio 01 Baseline",
        provenance_refs=["docs/runtime/monetization-opportunity-portfolio.md"],
        related_opportunity_id="airbnb-experiences-photography",
        related_project="Commercial Photography",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "What seasonal booking demand and calendar utilization exist in CDMX?",
            "What are net platform service fees and optimal ticket prices per seat?",
        ],
        expected_output="Experience listing outline and unit economics model.",
        decision_type="COMMERCIAL_ALLOCATION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-MON-010",
        title="LATAM Prediction Markets Platform Feasibility",
        category=BacklogCategory.MONETIZATION,
        priority=BacklogPriority.P1,
        status=BacklogStatus.BLOCKED,
        objective="Evaluate localized prediction market exchange for Latin American event contracts.",
        origin="Portfolio 01 Baseline",
        provenance_refs=["docs/runtime/monetization-opportunity-portfolio.md"],
        related_opportunity_id="prediction-markets-latam",
        related_project="Prediction Engine",
        dependencies=["Regulatory Licensing Gate"],
        blocked_by=["Regulatory and licensing authorization required in target jurisdictions."],
        research_questions=[
            "What jurisdictional gaming and financial derivatives frameworks apply?",
            "What banking rails and fiat onramps are legally accessible?",
        ],
        expected_output="Jurisdictional compliance memo and capital requirement model.",
        decision_type="GOVERNANCE_GATE",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-MON-011",
        title="Systematic Arbitrage Engine Feasibility",
        category=BacklogCategory.MONETIZATION,
        priority=BacklogPriority.P1,
        status=BacklogStatus.BLOCKED,
        objective="Build systematic cross-venue digital asset arbitrage strategies.",
        origin="Portfolio 01 Baseline",
        provenance_refs=["docs/runtime/monetization-opportunity-portfolio.md"],
        related_opportunity_id="arbitrage-engine",
        related_project="Trade Executor",
        dependencies=["Arbitrage Dependency Gate", "Trading Strategy Hardening"],
        blocked_by=["Arbitrage implementation blocked until execution latency and fee gates resolved."],
        research_questions=[
            "What execution latency is required to capture cross-exchange spreads?",
            "What VIP maker/taker fee tiers are necessary to prevent fee erosion?",
        ],
        expected_output="Spread capture model and venue colocation requirements.",
        decision_type="GOVERNANCE_GATE",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-MON-012",
        title="Section 8 Residential Real Estate Subsidized Housing",
        category=BacklogCategory.MONETIZATION,
        priority=BacklogPriority.P1,
        status=BacklogStatus.BLOCKED,
        objective="Acquire and operate residential housing choice voucher properties for government-backed rental cash flow.",
        origin="Portfolio 01 Baseline",
        provenance_refs=["docs/runtime/monetization-opportunity-portfolio.md"],
        related_opportunity_id="section-8-real-estate",
        related_project="Real Estate Operations",
        dependencies=["Capital Acquisition Gate"],
        blocked_by=["Upfront property acquisition and mortgage financing capital required."],
        research_questions=[
            "What are HUD Fair Market Rents and cap rates in target Midwest submarkets?",
            "What downpayment and debt service coverage ratios are required?",
        ],
        expected_output="Submarket acquisition model and property management protocol.",
        decision_type="GOVERNANCE_GATE",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),

    # =========================================================================
    # 2. BUSINESS_VALIDATION
    # =========================================================================
    ResearchBacklogItem(
        item_id="RBACK-VAL-001",
        title="Locations Concierge CDMX Validation Pack",
        category=BacklogCategory.BUSINESS_VALIDATION,
        priority=BacklogPriority.P0,
        status=BacklogStatus.READY,
        objective="Execute systematic business validation for Locations Concierge in Mexico City across workflow, pricing, supply density, and willingness-to-pay.",
        origin="DFG Business Concepts",
        provenance_refs=[],  # Explicitly empty: provenance recovery required
        related_opportunity_id=None,
        related_project="Locations Concierge",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "What are the primary causes of sourcing loss and rework for CDMX production managers?",
            "Can a curated supply density cover approximately 80% of representative commercial briefs?",
            "What competitor pricing and fee splits exist in Mexico City location scouting?",
        ],
        expected_output="Locations Concierge validation pack with 15-20 interview protocol, 5 shadowed briefs contract, mystery shopping comparison, and 20-brief replay spec.",
        decision_type="VALIDATION_GATE",
        created_at="2026-09-17",
        updated_at="2026-09-17",
        notes="Expansion outside CDMX remains strictly gated until CDMX validation passes.",
    ),
    ResearchBacklogItem(
        item_id="RBACK-VAL-002",
        title="DealHunter Business Models & Monetization Mechanics",
        category=BacklogCategory.BUSINESS_VALIDATION,
        priority=BacklogPriority.P1,
        status=BacklogStatus.NEEDS_EVIDENCE,
        objective="Validate business model archetypes for DealHunter property and asset sourcing tooling.",
        origin="DFG Strategic Vision",
        provenance_refs=[],  # Missing provenance
        related_opportunity_id=None,
        related_project="DealHunter",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "What transactional commission or subscription model best aligns with deal sourcers?",
            "What data feeds are required to reliably identify off-market discount assets?",
        ],
        expected_output="DealHunter unit economics model and customer segment analysis.",
        decision_type="VALIDATION_GATE",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-VAL-003",
        title="External Real-World Build Pilot",
        category=BacklogCategory.BUSINESS_VALIDATION,
        priority=BacklogPriority.P1,
        status=BacklogStatus.NEEDS_EVIDENCE,
        objective="Validate end-to-end execution of a scoped external client software delivery pilot via Lucius/FP Labs.",
        origin="Lucius Pilot Evaluations",
        provenance_refs=["docs/runtime/monetization-opportunity-portfolio.md"],
        related_opportunity_id="fp-labs-external-services",
        related_project="FP Labs",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "How effectively can an external brief be translated into deterministic Lucius tasks?",
            "What client communication overhead is required during supervised delivery?",
        ],
        expected_output="Pilot project postmortem and client delivery SLA standard.",
        decision_type="VALIDATION_GATE",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-VAL-004",
        title="Capability Gap Analysis from Real Client Briefs",
        category=BacklogCategory.BUSINESS_VALIDATION,
        priority=BacklogPriority.P1,
        status=BacklogStatus.NEEDS_EVIDENCE,
        objective="Analyze real-world client requests to identify recurring engineering gaps in existing DFG tools.",
        origin="FP Labs Intake",
        provenance_refs=[],
        related_opportunity_id="fp-labs-external-services",
        related_project="FP Labs",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "What technical capabilities are most frequently requested by automation clients?",
            "Which missing capabilities have the highest reuse value across DFG projects?",
        ],
        expected_output="DFG engineering capability gap matrix with reuse scores.",
        decision_type="CAPABILITY_SPECIFICATION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-VAL-005",
        title="International Creative Market Entry Research",
        category=BacklogCategory.BUSINESS_VALIDATION,
        priority=BacklogPriority.P2,
        status=BacklogStatus.QUEUED,
        objective="Evaluate expansion of DFG creative production services into international commercial markets (US/Europe remote).",
        origin="DFG Strategic Vision",
        provenance_refs=[],
        related_opportunity_id=None,
        related_project="Commercial Photography",
        dependencies=["Locations Concierge CDMX Validation"],
        blocked_by=[],
        research_questions=[
            "What cross-border payment, tax withholding, and contracting hurdles exist?",
            "What pricing arbitrage exists between CDMX production cost and US client budgets?",
        ],
        expected_output="International creative market entry memo and legal entity structure.",
        decision_type="VALIDATION_GATE",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),

    # =========================================================================
    # 3. TECHNOLOGY_SCOUT
    # =========================================================================
    ResearchBacklogItem(
        item_id="RBACK-TECH-001",
        title="Scrapling Web Scraping & Evasion Library Scout",
        category=BacklogCategory.TECHNOLOGY_SCOUT,
        priority=BacklogPriority.P0,
        status=BacklogStatus.READY,
        objective="Evaluate Scrapling Python library for upgrading Darwin's source content acquisition and anti-bot evasion stack.",
        origin="Darwin Technology Scout Backlog",
        provenance_refs=[],  # Missing explicit repo doc; research requirement created
        related_opportunity_id=None,
        related_project="Darwin Acquisition",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "Does Scrapling provide headless browser automation or HTTP-level fingerprinting?",
            "What is its license, Python 3.11+ compatibility, and maintenance status?",
            "Can it be adapted cleanly behind Darwin's existing AcquisitionService boundary?",
        ],
        expected_output="Standardized Tech Scout Assessment and recommendation.",
        decision_type="TECHNOLOGY_SELECTION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-TECH-002",
        title="Vibe-Trading Architecture Scout",
        category=BacklogCategory.TECHNOLOGY_SCOUT,
        priority=BacklogPriority.P0,
        status=BacklogStatus.READY,
        objective="Recover provenance and evaluate Vibe-Trading architecture for potential algorithmic or signal reuse in Trade Executor.",
        origin="Darwin Technology Scout Backlog",
        provenance_refs=[],  # Missing explicit repo doc; research requirement created
        related_opportunity_id="trading-strategy-hardening",
        related_project="Trade Executor",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "What is the exact repository or documentation reference for Vibe-Trading?",
            "What strategy logic or order-routing primitives does it demonstrate?",
            "Does it provide reusable patterns compatible with Node/SQLite Trade Executor?",
        ],
        expected_output="Provenance recovery report and Tech Scout Assessment.",
        decision_type="TECHNOLOGY_SELECTION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-TECH-003",
        title="TikTok Shop Affiliate Tooling Layer Scout",
        category=BacklogCategory.TECHNOLOGY_SCOUT,
        priority=BacklogPriority.P1_HIGH,
        status=BacklogStatus.NEEDS_EVIDENCE,
        objective="Evaluate external AI creative generators, caption stylers, and TikTok product trend scrapers for pipeline integration.",
        origin="Production Engine Backlog",
        provenance_refs=[],
        related_opportunity_id="tiktok-shop-affiliate-creative",
        related_project="Billy Production Engine",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "What programmatic APIs exist for automated TikTok Shop product discovery?",
            "Can video variant generation be handled locally without per-clip subscription fees?",
        ],
        expected_output="Tooling matrix with API accessibility and license audit.",
        decision_type="TECHNOLOGY_SELECTION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-TECH-004",
        title="Fomo Marketing Automation Scout",
        category=BacklogCategory.TECHNOLOGY_SCOUT,
        priority=BacklogPriority.P1,
        status=BacklogStatus.NEEDS_EVIDENCE,
        objective="Evaluate Fomo social proof and live conversion notification architectures.",
        origin="Darwin Technology Scout Backlog",
        provenance_refs=[],
        related_opportunity_id=None,
        related_project="Darwin Acquisition",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "What public APIs or open-source equivalents exist for real-time purchase popups?",
            "Is there actionable conversion uplift data for digital products?",
        ],
        expected_output="Tech Scout Assessment on social proof mechanisms.",
        decision_type="TECHNOLOGY_SELECTION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-TECH-005",
        title="Open Generative AI Framework Scout",
        category=BacklogCategory.TECHNOLOGY_SCOUT,
        priority=BacklogPriority.P1,
        status=BacklogStatus.NEEDS_EVIDENCE,
        objective="Investigate open-source generative AI toolkits for synthetic video and avatar generation.",
        origin="Billy Production Engine Backlog",
        provenance_refs=[],
        related_opportunity_id="production-engine-acceleration",
        related_project="Billy Production Engine",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "What open-source video models achieve commercial-grade avatar lipsync?",
            "Can local inference run cost-effectively on Apple Silicon or cloud GPUs?",
        ],
        expected_output="Open-source video model benchmark comparison.",
        decision_type="TECHNOLOGY_SELECTION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-TECH-006",
        title="Zeely Growth Tooling Scout",
        category=BacklogCategory.TECHNOLOGY_SCOUT,
        priority=BacklogPriority.P1,
        status=BacklogStatus.NEEDS_EVIDENCE,
        objective="Evaluate Zeely's mobile-first AI advertising generation and landing page patterns.",
        origin="Darwin Technology Scout Backlog",
        provenance_refs=[],
        related_opportunity_id=None,
        related_project="Commercial Photography",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "What creative templates achieve highest click-through rates in e-commerce?",
            "Can Zeely's multi-variant ad assembly workflow be copied programmatically?",
        ],
        expected_output="Architectural pattern analysis for multi-variant ad rendering.",
        decision_type="TECHNOLOGY_SELECTION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-TECH-007",
        title="Claude Ads Copy Optimization Scout",
        category=BacklogCategory.TECHNOLOGY_SCOUT,
        priority=BacklogPriority.P1,
        status=BacklogStatus.NEEDS_EVIDENCE,
        objective="Assess structured prompt architectures for generating high-converting programmatic advertising copy variants.",
        origin="Darwin Technology Scout Backlog",
        provenance_refs=[],
        related_opportunity_id=None,
        related_project="Production Engine",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "What prompt evaluation frameworks prevent hallucinations in product claims?",
            "How can copy variants be scored against historic conversion performance?",
        ],
        expected_output="Prompt engineering template and deterministic validation rubric.",
        decision_type="TECHNOLOGY_SELECTION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-TECH-008",
        title="DefiLlama API & Yield Analytics Scout",
        category=BacklogCategory.TECHNOLOGY_SCOUT,
        priority=BacklogPriority.P1_P2,
        status=BacklogStatus.NEEDS_EVIDENCE,
        objective="Audit DefiLlama free/open REST APIs for TVL, protocol yields, and digital asset liquidity tracking.",
        origin="Darwin Market Intelligence Backlog",
        provenance_refs=[],
        related_opportunity_id="trading-strategy-hardening",
        related_project="Trading Dashboard",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "What rate limits and endpoint guarantees does the open API provide?",
            "Can protocol TVL changes serve as leading indicators for token momentum?",
        ],
        expected_output="DefiLlama API adapter specification and data schema.",
        decision_type="TECHNOLOGY_SELECTION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-TECH-009",
        title="CoinGecko API Market Pricing Scout",
        category=BacklogCategory.TECHNOLOGY_SCOUT,
        priority=BacklogPriority.P1_P2,
        status=BacklogStatus.NEEDS_EVIDENCE,
        objective="Evaluate CoinGecko public vs pro API tiers for market cap, volume, and multi-asset price feeds.",
        origin="Trading Dashboard Backlog",
        provenance_refs=[],
        related_opportunity_id="trading-strategy-hardening",
        related_project="Trading Dashboard",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "What are current demo/free tier rate limits on price endpoints?",
            "What latency and uptime guarantees govern the public feed?",
        ],
        expected_output="CoinGecko endpoint audit and fallback configuration spec.",
        decision_type="TECHNOLOGY_SELECTION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-TECH-010",
        title="CoinGlass Derivatives Data Scout",
        category=BacklogCategory.TECHNOLOGY_SCOUT,
        priority=BacklogPriority.P1_P2,
        status=BacklogStatus.NEEDS_EVIDENCE,
        objective="Investigate CoinGlass funding rates, open interest, and liquidation heatmap data feeds.",
        origin="Trade Executor Backlog",
        provenance_refs=[],
        related_opportunity_id="trading-strategy-hardening",
        related_project="Trade Executor",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "Does CoinGlass provide programmatic websocket/REST access for futures open interest?",
            "Can funding rate extremes improve the win rate of EMA/RSI trading strategies?",
        ],
        expected_output="Derivatives data intake specification and cost audit.",
        decision_type="TECHNOLOGY_SELECTION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-TECH-011",
        title="Tokenomist Token Unlock Analytics Scout",
        category=BacklogCategory.TECHNOLOGY_SCOUT,
        priority=BacklogPriority.P1_P2,
        status=BacklogStatus.NEEDS_EVIDENCE,
        objective="Evaluate Tokenomist (formerly TokenUnlocks) for programmatic token emission and cliff vesting data.",
        origin="Darwin Intelligence Backlog",
        provenance_refs=[],
        related_opportunity_id=None,
        related_project="Trading Dashboard",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "What API access exists for major token cliff unlock dates and amounts?",
            "What historical price impact is correlated with large unlock events?",
        ],
        expected_output="Token unlock event schema and calendar adapter.",
        decision_type="TECHNOLOGY_SELECTION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-TECH-012",
        title="Bubblemaps On-Chain Clustering Scout",
        category=BacklogCategory.TECHNOLOGY_SCOUT,
        priority=BacklogPriority.P1_P2,
        status=BacklogStatus.NEEDS_EVIDENCE,
        objective="Assess Bubblemaps supply distribution and wallet clustering visualization tools for token risk auditing.",
        origin="Darwin Intelligence Backlog",
        provenance_refs=[],
        related_opportunity_id=None,
        related_project="Trading Dashboard",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "Does Bubblemaps expose an API for wallet cluster concentration scores?",
            "Can cluster metrics identify insider-held supply before market entry?",
        ],
        expected_output="Wallet graph risk scoring rubric.",
        decision_type="TECHNOLOGY_SELECTION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-TECH-013",
        title="Messari Protocol Research & Metrics Scout",
        category=BacklogCategory.TECHNOLOGY_SCOUT,
        priority=BacklogPriority.P1_P2,
        status=BacklogStatus.NEEDS_EVIDENCE,
        objective="Investigate Messari fundamental data feeds and protocol quarterly reporting metrics.",
        origin="Darwin Intelligence Backlog",
        provenance_refs=[],
        related_opportunity_id=None,
        related_project="Trading Dashboard",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "What endpoints are accessible under basic developer subscriptions?",
            "Can standardized financial metrics (P/S, revenue, fees) be extracted programmatically?",
        ],
        expected_output="Fundamental crypto valuation metrics adapter.",
        decision_type="TECHNOLOGY_SELECTION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-TECH-014",
        title="Dune Analytics SQL Engine Scout",
        category=BacklogCategory.TECHNOLOGY_SCOUT,
        priority=BacklogPriority.P2,
        status=BacklogStatus.QUEUED,
        objective="Evaluate Dune Analytics API for executing parameterized SQL queries against decoded on-chain tables.",
        origin="Darwin Intelligence Backlog",
        provenance_refs=[],
        related_opportunity_id=None,
        related_project="Darwin Research Engine",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "What credit consumption model governs the Dune API?",
            "Can custom queries be triggered and parsed into Darwin EvidenceUnits?",
        ],
        expected_output="Dune SQL query execution bridge specification.",
        decision_type="TECHNOLOGY_SELECTION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-TECH-015",
        title="Conway Automaton Autonomous Agent Architecture Scout",
        category=BacklogCategory.TECHNOLOGY_SCOUT,
        priority=BacklogPriority.P2,
        status=BacklogStatus.QUEUED,
        objective="Study Conway / Automaton architectural patterns for stateful multi-agent execution.",
        origin="Lucius Engineering Backlog",
        provenance_refs=[],
        related_opportunity_id=None,
        related_project="Lucius Engineering",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "What state persistence primitives does Conway implement?",
            "Are there lightweight supervisor patterns relevant to Lucius or Darwin?",
        ],
        expected_output="Architectural pattern evaluation report.",
        decision_type="TECHNOLOGY_SELECTION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-TECH-016",
        title="Cryptoneur Gas Intelligence Scout",
        category=BacklogCategory.TECHNOLOGY_SCOUT,
        priority=BacklogPriority.P2,
        status=BacklogStatus.QUEUED,
        objective="Assess Cryptoneur gas fee prediction and EVM network congestion models.",
        origin="Darwin Intelligence Backlog",
        provenance_refs=[],
        related_opportunity_id="trading-strategy-hardening",
        related_project="Trade Executor",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "How accurate are short-term gas price estimations during high volatility?",
            "Can gas models optimize transaction timing for on-chain rebalancing?",
        ],
        expected_output="Gas model evaluation report.",
        decision_type="TECHNOLOGY_SELECTION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),

    # =========================================================================
    # 4. INTELLIGENCE_CAPABILITIES
    # =========================================================================
    ResearchBacklogItem(
        item_id="RBACK-INT-001",
        title="Prediction Market Intelligence Capability",
        category=BacklogCategory.INTELLIGENCE_CAPABILITIES,
        priority=BacklogPriority.P1,
        status=BacklogStatus.QUEUED,
        objective="Design Darwin intelligence subsystem to monitor, ingest, and calibrate odds from global prediction markets (Polymarket, Kalshi).",
        origin="Darwin Strategic Roadmap",
        provenance_refs=[],
        related_opportunity_id="prediction-markets-latam",
        related_project="Darwin Research Engine",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "What public websocket streams provide real-time order book odds on Polymarket/Kalshi?",
            "Can prediction market probability shifts serve as leading macro sentiment signals?",
        ],
        expected_output="Prediction market odds ingestion specification and claim extractor.",
        decision_type="CAPABILITY_SPECIFICATION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-INT-002",
        title="Market Intelligence Capability",
        category=BacklogCategory.INTELLIGENCE_CAPABILITIES,
        priority=BacklogPriority.P2,
        status=BacklogStatus.QUEUED,
        objective="Systematize multi-exchange spot and futures market intelligence feeds into Darwin evidence models.",
        origin="Darwin Strategic Roadmap",
        provenance_refs=[],
        related_opportunity_id="trading-strategy-hardening",
        related_project="Darwin Research Engine",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "How to structure market volume anomalies into verifiable Darwin claims?",
        ],
        expected_output="Market intelligence claim constructor.",
        decision_type="CAPABILITY_SPECIFICATION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-INT-003",
        title="Derivatives Intelligence Capability",
        category=BacklogCategory.INTELLIGENCE_CAPABILITIES,
        priority=BacklogPriority.P2,
        status=BacklogStatus.QUEUED,
        objective="Build automated funding rate, term structure, and options skew surveillance.",
        origin="Darwin Strategic Roadmap",
        provenance_refs=[],
        related_opportunity_id="trading-strategy-hardening",
        related_project="Darwin Research Engine",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "What funding rate divergence thresholds indicate imminent liquidation cascades?",
        ],
        expected_output="Derivatives surveillance feed specification.",
        decision_type="CAPABILITY_SPECIFICATION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-INT-004",
        title="On-Chain Intelligence Capability",
        category=BacklogCategory.INTELLIGENCE_CAPABILITIES,
        priority=BacklogPriority.P2,
        status=BacklogStatus.QUEUED,
        objective="Extract structured whale accumulation and exchange net-flow claims from blockchain explorers.",
        origin="Darwin Strategic Roadmap",
        provenance_refs=[],
        related_opportunity_id=None,
        related_project="Darwin Research Engine",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "Which on-chain flow metrics have statistically significant predictive power?",
        ],
        expected_output="On-chain flow evidence extractor.",
        decision_type="CAPABILITY_SPECIFICATION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-INT-005",
        title="Tokenomics Intelligence Capability",
        category=BacklogCategory.INTELLIGENCE_CAPABILITIES,
        priority=BacklogPriority.P2,
        status=BacklogStatus.QUEUED,
        objective="Model circulating supply inflation schedules, staking yield decay, and treasury runway.",
        origin="Darwin Strategic Roadmap",
        provenance_refs=[],
        related_opportunity_id=None,
        related_project="Darwin Research Engine",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "How to structure supply schedule vesting cliffs into quantitative valuation discounts?",
        ],
        expected_output="Tokenomics evaluation framework.",
        decision_type="CAPABILITY_SPECIFICATION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-INT-006",
        title="Wallet Graph Intelligence Capability",
        category=BacklogCategory.INTELLIGENCE_CAPABILITIES,
        priority=BacklogPriority.P2,
        status=BacklogStatus.QUEUED,
        objective="Construct entity-resolved wallet clustering graphs to track smart money and insider distribution.",
        origin="Darwin Strategic Roadmap",
        provenance_refs=[],
        related_opportunity_id=None,
        related_project="Darwin Research Engine",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "Can heuristics group sibling addresses without high false-positive clustering?",
        ],
        expected_output="Wallet graph clustering schema.",
        decision_type="CAPABILITY_SPECIFICATION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-INT-007",
        title="DeFi Intelligence Capability",
        category=BacklogCategory.INTELLIGENCE_CAPABILITIES,
        priority=BacklogPriority.P2,
        status=BacklogStatus.QUEUED,
        objective="Monitor automated market maker liquidity depth, pool impermanent loss, and lending protocol bad debt risk.",
        origin="Darwin Strategic Roadmap",
        provenance_refs=[],
        related_opportunity_id=None,
        related_project="Darwin Research Engine",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "What automated triggers flag liquidity drain events in major pools?",
        ],
        expected_output="DeFi health monitoring specification.",
        decision_type="CAPABILITY_SPECIFICATION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-INT-008",
        title="Fundamental Asset Intelligence Capability",
        category=BacklogCategory.INTELLIGENCE_CAPABILITIES,
        priority=BacklogPriority.P2,
        status=BacklogStatus.QUEUED,
        objective="Synthesize traditional financial reporting metrics for tokenized and physical DFG investment assets.",
        origin="Darwin Strategic Roadmap",
        provenance_refs=[],
        related_opportunity_id=None,
        related_project="Darwin Research Engine",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "What standard accounting adjustments are required when comparing Web3 protocol revenue to traditional SaaS?",
        ],
        expected_output="Fundamental asset scoring rubric.",
        decision_type="CAPABILITY_SPECIFICATION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-INT-009",
        title="Macro Intelligence Capability",
        category=BacklogCategory.INTELLIGENCE_CAPABILITIES,
        priority=BacklogPriority.P2,
        status=BacklogStatus.QUEUED,
        objective="Track central bank interest rate expectations, treasury yields, and global liquidity indicators.",
        origin="Darwin Strategic Roadmap",
        provenance_refs=[],
        related_opportunity_id=None,
        related_project="Darwin Research Engine",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "Which macro liquidity metrics exhibit highest cross-correlation with digital asset drawdowns?",
        ],
        expected_output="Macro liquidity dashboard contract.",
        decision_type="CAPABILITY_SPECIFICATION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-INT-010",
        title="News & Narrative Intelligence Capability",
        category=BacklogCategory.INTELLIGENCE_CAPABILITIES,
        priority=BacklogPriority.P2,
        status=BacklogStatus.QUEUED,
        objective="Detect nascent narrative clusters across crypto news and social feeds prior to peak retail attention.",
        origin="Darwin Strategic Roadmap",
        provenance_refs=[],
        related_opportunity_id=None,
        related_project="Darwin Research Engine",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "What cluster density growth rates identify emerging narrative trends?",
        ],
        expected_output="Narrative momentum detection engine specification.",
        decision_type="CAPABILITY_SPECIFICATION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
    ResearchBacklogItem(
        item_id="RBACK-INT-011",
        title="Telegram Opportunity Scout Capability",
        category=BacklogCategory.INTELLIGENCE_CAPABILITIES,
        priority=BacklogPriority.P2,
        status=BacklogStatus.QUEUED,
        objective="Automate keyword scanning and arbitrage alert detection across monitored public Telegram crypto channels.",
        origin="FPCC Strategic Roadmap",
        provenance_refs=[],
        related_opportunity_id="fpcriptoclub-monetization",
        related_project="Trade Executor",
        dependencies=[],
        blocked_by=[],
        research_questions=[
            "Can Telegram channel messages be parsed in real time without triggering account limits?",
        ],
        expected_output="Telegram alert ingestion specification.",
        decision_type="CAPABILITY_SPECIFICATION",
        created_at="2026-09-17",
        updated_at="2026-09-17",
    ),
]
